ALTER USER SQL_NETAPPS_SOFKA ACCOUNT UNLOCK;
ALTER USER SQL_PERFORMANCE_SOFKA ACCOUNT UNLOCK;
ALTER USER SQL_PRODUCTOWNER_SOFKA ACCOUNT UNLOCK;
ALTER USER SQL_QAAUTOMATIZATION_SOFKA ACCOUNT UNLOCK;
ALTER USER SQL_QAFUNCTIONAL_SOFKA ACCOUNT UNLOCK;
ALTER USER SQL_WEBSERVICES_SOFKA ACCOUNT UNLOCK;

SELECT username, account_status, lock_date, expiry_date, default_tablespace, temporary_tablespace, created 
  FROM dba_users WHERE username IN ('SQL_NETAPPS_SOFKA','SQL_PERFORMANCE_SOFKA','SQL_PRODUCTOWNER_SOFKA'
                                   ,'SQL_QAAUTOMATIZATION_SOFKA','SQL_QAFUNCTIONAL_SOFKA','SQL_WEBSERVICES_SOFKA');