-- Estraer datos de TAG XML de campo CLOB
SELECT DISTINCT xt.*
  FROM INTEGRACION.LOG_INT_MSG x,
       XMLTABLE('/DATOS_BDP/PRODUCCION_QUEMA/ESTACIONES/ESTACION' PASSING
                XMLTYPE(x.xmlcom) COLUMNS "ESTACION" VARCHAR2(50) PATH 'NOMBRE') xt
  WHERE tipoevento LIKE '%QUEM%'
   AND TO_CHAR(fechaejecucion, 'DD/MM/YYYY') = '04/12/2015'; 
