ALTER USER SQL_PRODUCTOWNER_SOFKA IDENTIFIED BY m3tr02021m33;
ALTER USER SQL_PERFORMANCE_SOFKA IDENTIFIED BY m3tr02021m333;
ALTER USER SQL_QAFUNCTIONAL_SOFKA IDENTIFIED BY m3tr04021m3;
ALTER USER SQL_QAAUTOMATIZATION_SOFKA IDENTIFIED BY m3tr02022m3d33;
ALTER USER SQL_WEBSERVICES_SOFKA IDENTIFIED BY "m3tr0202127m33";
ALTER USER SQL_NETAPPS_SOFKA IDENTIFIED BY m3trm3d3ll1n3;
ALTER USER SQL_SOFKA IDENTIFIED BY "$$$kmpJeVLbb3";

/*SELECT username, account_status, lock_date, expiry_date, default_tablespace, temporary_tablespace, created 
  FROM dba_users WHERE username IN ('SQL_NETAPPS_SOFKA','SQL_PERFORMANCE_SOFKA','SQL_PRODUCTOWNER_SOFKA'
                                   ,'SQL_QAAUTOMATIZATION_SOFKA','SQL_QAFUNCTIONAL_SOFKA','SQL_WEBSERVICES_SOFKA','SQL_SOFKA');*/